# Generated by Django 3.1.3 on 2022-01-30 23:29

import companies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompany',
            fields=[
                ('id', models.CharField(default=companies.models.UniqueID2, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('basecompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.basecompany')),
            ],
            bases=('companies.basecompany',),
        ),
        migrations.CreateModel(
            name='SuperCompany',
            fields=[
                ('basecompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.basecompany')),
            ],
            bases=('companies.basecompany',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(default=companies.models.UniqueID, editable=False, max_length=7, unique=True)),
                ('qrID', models.CharField(default=companies.models.UniqueID, max_length=7, unique=True)),
                ('simCard', models.CharField(blank=True, max_length=20, null=True)),
                ('firmWareVersion', models.CharField(default='v0', max_length=7)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.company')),
            ],
        ),
    ]
