# Generated by Django 3.1.3 on 2022-02-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_leasingfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='leaseCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.supercompany'),
        ),
    ]
