# Generated by Django 3.1.3 on 2022-02-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_device_leasecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='device',
            name='leaseCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='companies.supercompany'),
        ),
    ]
