# Generated by Django 3.1.3 on 2022-06-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20220321_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecompany',
            name='phone',
            field=models.TextField(default=7777777, max_length=11),
            preserve_default=False,
        ),
    ]
