# Generated by Django 3.1.3 on 2022-08-22 15:13

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_basecompany_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompany',
            name='id',
            field=models.CharField(default=companies.models.UniqueID2, max_length=20, primary_key=True, serialize=False),
        ),
    ]
