# Generated by Django 3.1.3 on 2022-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20220822_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='simCard',
            field=models.CharField(default=7777777, max_length=20),
            preserve_default=False,
        ),
    ]
