# Generated by Django 3.1.3 on 2022-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20220829_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='simCard',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
